linters:
  disable-all: true
  enable:
  - bodyclose
  - cyclop
  - goconst
  - godox
  - gofmt
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - prealloc
  - revive
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace

run:
  timeout: 10m
  modules-download-mode: readonly