// Code generated by mockery v2.35.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IFoo is an autogenerated mock type for the IFoo type
type IFoo struct {
	mock.Mock
}

// Process provides a mock function with given fields: input
func (_m *IFoo) Process(input int) int {
	ret := _m.Called(input)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// NewIFoo creates a new instance of IFoo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFoo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFoo {
	mock := &IFoo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
